### ISSUE TITLE
???

### ISSUE THREAD

**Issue by Trophonix** [Gloryness/Gloryness#1]
My name is Lucas, I own the Lab Games Minecraft server. Seems you got into an argument with a discord bot dev who has been working on a bot project for us, and in retaliation, you've destroyed my discord server. You banned all our players and replaced the channels with a bunch of voice channels called "FUCK MY THROAT - Rough and Sloppy Deepthroat with tied hands". 

Who does that??? What are you 12 years old?

I had nothing to do with your petty disagreement, and I don't understand why you chose to take your anger out on my community. You should be ashamed. No respectable developer would do such a thing.

**Comment by Gloryness** [comment]
This has nothing to do with me? I literally couldn't care less about whatever that argument was. What happened happened I'm not gonna bother trying to be their friends again since they blocked me. I'm not sure why you all are assuming I did whatever happened since I would never do anything like that and like you said it's disrespectful. However can see very clearly as to why you'd think it's me and obviously I can't change that.
